# Generated by Django 5.2.5 on 2025-08-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
